trigger:
- master
- develop

resources:
  repositories:
  - repository: testalproject
    type: github
    name: DavidFeldhoff/test-al-project
    branch: master
    endpoint: github.com_DavidFeldhoff

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
- checkout: testalproject

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
- bash: |
    echo ">>> Compile vscode-test"
    yarn && yarn compile
    echo ">>> Compiled vscode-test"
    echo ">>> Run tests"
    # yarn && yarn compile && yarn test # currently not working due to calls to the definition provider (only works locally)
  displayName: Run Tests
  workingDirectory: al-codeactions
  env:
    DISPLAY: ':99.0'