trigger:
- master

resources:
  repositories:
  - repository: test-al-project
    type: github
    name: DavidFeldhoff/test-al-project
    branch: master
    endpoint: github.com_DavidFeldhoff

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
- checkout: test-al-project

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    sudo snap install --classic code
  displayName: Install VS Code for Linux
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
- powershell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    choco install vscode
  displayName: Install VS Code for Windows
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
- bash: |
    code --install-extension microsoft.al
  displayName: Install Extension microsoft.al
- bash: |
    code --install-extension andrzejzwierzchowski.al-code-outline
  displayName: Install Extension andrzejzwierzchowski.al-code-outline
- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
- bash: |
    echo ">>> Compile vscode-test"
    yarn && yarn compile
    echo ">>> Compiled vscode-test"
    echo ">>> Run tests"
    yarn && yarn compile && yarn test
  displayName: Run Tests
  workingDirectory: al-codeactions
  env:
    DISPLAY: ':99.0'