trigger:
- master

resources:
  repositories:
  - repository: test-al-project
    type: github
    name: DavidFeldhoff/test-al-project
    branch: master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
- checkout: test-al-project

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile vscode-test"
    yarn && yarn compile
    echo ">>> Compiled vscode-test"
    echo ">>> Run sample integration test"
    yarn && yarn compile && yarn copyfiles && yarn test
  displayName: Run Tests
  workingDirectory: al-codeactions
  env:
    DISPLAY: ':99.0'